# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 20:46
from __future__ import unicode_literals

import assmat.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BulletinSalaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(verbose_name='Date début')),
                ('date_fin', models.DateField(verbose_name='Date fin')),
                ('accomptes_verses', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Accomptes versés dans le mois')),
                ('nb_km', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name="Nombre de km pour l'indemnité de déplacement")),
                ('indemnite_rupture', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Indemnités de rupture ou de licenciement')),
                ('commentaire', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Commentaire')),
                ('cp_nb_mois_travailles', models.IntegerField(default=0, verbose_name='CP (N) : Nombre de mois travaillés')),
                ('cp_nb_semaines_travailles', models.IntegerField(default=0, verbose_name='CP (N) : Nombre de semaines travaillées')),
                ('cp_nb_jours_enfants', models.IntegerField(default=0, verbose_name='CP (N) : Nombre de jours enfants de - de 15 ans')),
                ('cp_nb_fractionnement', models.IntegerField(default=0, verbose_name='CP (N) : Nombre de jours de fractionnement')),
                ('cp_nb_pris', models.IntegerField(default=0, verbose_name='CP (N) : Nombre de jours pris')),
                ('cp1_nb_mois_travailles', models.IntegerField(default=0, verbose_name='CP (N-1) : Nombre de mois travaillés')),
                ('cp1_nb_semaines_travailles', models.IntegerField(default=0, verbose_name='CP (N-1) : Nombre de semaines travaillées')),
                ('cp1_nb_jours_enfants', models.IntegerField(default=0, verbose_name='CP (N-1) : Nombre de jours enfants de - de 15 ans')),
                ('cp1_nb_fractionnement', models.IntegerField(default=0, verbose_name='CP (N-1) : Nombre de jours de fractionnement')),
                ('cp1_nb_pris', models.IntegerField(default=0, verbose_name='CP (N-1) : Nombre de jours pris')),
                ('net_a_payer', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Net à payer')),
                ('net_imposable', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Net imposable')),
                ('cumul_net_imposable', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Cumul annuel net imposable')),
                ('date_paiement', models.DateField(verbose_name='Date de paiement')),
                ('numero_cheque_virement', models.CharField(blank=True, max_length=256, null=True, verbose_name='Numéro du chèque ou virement')),
                ('cumul_nb_semaines_travaillees', models.IntegerField(verbose_name='Nombre de semaines travaillées depuis le 1er janvier')),
                ('cumul_nb_jours_plus_8h', models.IntegerField(verbose_name='Cumul annuel du nombre de jours travaillés de 8h et plus')),
                ('cumul_nb_jours_moins_8h', models.IntegerField(verbose_name='Cumul annuel du nombre de jours travaillés de moins de 8h')),
                ('pdf', models.FileField(null=True, upload_to=assmat.models.repertoire_upload_bulletin_salaire_pdf, verbose_name='Fichier PDF')),
            ],
        ),
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_prenom_employeur', models.CharField(max_length=256, verbose_name='Employeur : Nom et Prénom')),
                ('adresse_1_employeur', models.CharField(max_length=256, verbose_name='Employeur : Adresse 1')),
                ('adresse_2_employeur', models.CharField(blank=True, max_length=256, null=True, verbose_name='Employeur : Adresse 2')),
                ('code_postal_employeur', models.CharField(max_length=6, verbose_name='Employeur : Code postal')),
                ('ville_employeur', models.CharField(max_length=128, verbose_name='Employeur : Ville')),
                ('numero_immatriculation_urssaf_employeur', models.CharField(blank=True, max_length=128, null=True, verbose_name="Employeur : N° d'immatriculation URSSAF")),
                ('numero_pajemploi_employeur', models.CharField(blank=True, max_length=128, null=True, verbose_name='Employeur : N° PAJEMPLOI')),
                ('urssaf_de_employeur', models.CharField(blank=True, max_length=128, null=True, verbose_name='Employeur : URSSAF de')),
                ('banque_employeur', models.CharField(max_length=128, verbose_name='Employeur : Banque')),
                ('jour_paiement', models.IntegerField(verbose_name='Jour de paiement du salaire dans le mois')),
                ('date_debut_contrat', models.DateField(verbose_name='Date début du contrat')),
                ('date_fin_contrat', models.DateField(null=True, verbose_name='Date fin du contrat')),
                ('nom_prenom_enfant', models.CharField(max_length=256, verbose_name="Nom et Prénom de l'enfant")),
                ('haut_rhin_bas_rhin_moselle', models.BooleanField(default=False, verbose_name="L'ass mat réside en Haut Rhin - Bas Rhin - Moselle")),
                ('nom_prenom_salarie', models.CharField(max_length=256, verbose_name='Salarié : Nom et Prénom')),
                ('adresse_1_salarie', models.CharField(max_length=256, verbose_name='Salarié : Adresse 1')),
                ('adresse_2_salarie', models.CharField(blank=True, max_length=256, null=True, verbose_name='Salarié : Adresse 2')),
                ('code_postal_salarie', models.CharField(max_length=6, verbose_name='Salarié : Code postal')),
                ('ville_salarie', models.CharField(max_length=128, verbose_name='Salarié : Ville')),
                ('numero_securite_sociale_salarie', models.CharField(max_length=15, verbose_name='Salarié : N° Sécurité Sociale')),
                ('nb_semaines_programmees', models.DecimalField(decimal_places=2, max_digits=2, verbose_name='Nombre de semaines programmées')),
                ('nb_heures_semaine', models.DecimalField(decimal_places=2, max_digits=2, verbose_name="Nombre d'heures par semaine")),
                ('nb_heures_supps_contractuelles_mois', models.DecimalField(decimal_places=2, default=0, max_digits=2, verbose_name="Nombre d'heures supplémentaires contractuelles par mois")),
                ('nb_heures_accueil_jour', models.DecimalField(decimal_places=2, max_digits=2, verbose_name="Nombre d'heures d'accueil par jour")),
                ('remuneration_horaire_brute', models.DecimalField(decimal_places=2, max_digits=2, verbose_name='Rémunération horaire brute')),
                ('majoration_heures_supps_contractuelles', models.DecimalField(decimal_places=2, default=100, max_digits=3, verbose_name='Majoration des heures supplémentaires contractuelles')),
                ('majoration_heures_supps_non_contractuelles', models.DecimalField(decimal_places=2, default=100, max_digits=3, verbose_name='Majoration des heureus supplémentaires non contractuelles')),
                ('majoration_heures_complementaires', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Majoration des heures complémentaires')),
                ('indemnite_entretien', models.DecimalField(decimal_places=2, default=0, max_digits=2, verbose_name="Indemnité d'entretien")),
                ('indemnite_entretien_heures_supps', models.DecimalField(decimal_places=2, default=0, max_digits=2, verbose_name="Indemnité d'entretien par heure supplémentaire")),
                ('indemnite_repas', models.DecimalField(decimal_places=2, default=0, max_digits=2, verbose_name='Indemnité de repas')),
                ('indemnite_gouter', models.DecimalField(decimal_places=2, default=0, max_digits=2, verbose_name='Indemnité de goûter')),
                ('indemnite_km', models.DecimalField(decimal_places=2, default=0, max_digits=2, verbose_name='Indemnité de déplacement kilométrique')),
                ('jours_normalement_travailles', models.PositiveIntegerField(default=124, max_length=128, verbose_name='Jours de la semaine normalement travaillés')),
                ('utilisateurs', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Utilisateurs')),
            ],
        ),
        migrations.CreateModel(
            name='JourTravail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('heures_effectuees', models.DecimalField(decimal_places=2, max_digits=2, verbose_name='Heures effectuées (hors complémentaires/supps)')),
                ('heures_complementaires', models.DecimalField(decimal_places=2, default=0, max_digits=2, verbose_name='Heures complémentaires')),
                ('heures_supplementaires', models.DecimalField(decimal_places=2, default=0, max_digits=2, verbose_name='Heures supplémentaires')),
                ('type', models.CharField(choices=[('T', 'Travaillé'), ('NT', 'Non Travaillé (week end)'), ('A.A.M.S.S.', 'Absence Ass.Mat.Sans Solde'), ('A.J.E.', 'Absence justifiée Enfant'), ('A.I.E.', 'Absence injustifiée Enfant'), ('C.S.S.', 'Congés sans solde'), ('C.P.', 'Congés payés'), ('S.D.A.M.', 'Semaine déduite Parents Empl.'), ('F.', 'Jour Férié chomé payé')], max_length=64, verbose_name='Type')),
                ('repas', models.BooleanField(default=False, verbose_name="L'enfant a eu un repas")),
                ('gouter', models.BooleanField(default=False, verbose_name="L'enfant a eu un goûter")),
                ('bulletin_salaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assmat.BulletinSalaire', verbose_name='Bulletin de salaire')),
            ],
        ),
        migrations.AddField(
            model_name='bulletinsalaire',
            name='contrat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assmat.Contrat', verbose_name='Contrat'),
        ),
    ]
