# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assmat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrat',
            name='jours_normalement_travailles',
            field=models.PositiveIntegerField(default=124, verbose_name='Jours de la semaine normalement travaillés'),
        ),
    ]
