# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assmat', '0002_auto_20170913_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrat',
            name='date_fin_contrat',
            field=models.DateField(blank=True, null=True, verbose_name='Date fin du contrat'),
        ),
    ]
