# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assmat', '0003_auto_20170913_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulletinsalaire',
            name='accomptes_verses',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Accomptes versés dans le mois'),
        ),
        migrations.AlterField(
            model_name='bulletinsalaire',
            name='cumul_net_imposable',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Cumul annuel net imposable'),
        ),
        migrations.AlterField(
            model_name='bulletinsalaire',
            name='indemnite_rupture',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Indemnités de rupture ou de licenciement'),
        ),
        migrations.AlterField(
            model_name='bulletinsalaire',
            name='nb_km',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name="Nombre de km pour l'indemnité de déplacement"),
        ),
        migrations.AlterField(
            model_name='bulletinsalaire',
            name='net_a_payer',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Net à payer'),
        ),
        migrations.AlterField(
            model_name='bulletinsalaire',
            name='net_imposable',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Net imposable'),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='indemnite_entretien',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name="Indemnité d'entretien"),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='indemnite_entretien_heures_supps',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name="Indemnité d'entretien par heure supplémentaire"),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='indemnite_gouter',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Indemnité de goûter'),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='indemnite_km',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Indemnité de déplacement kilométrique'),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='indemnite_repas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Indemnité de repas'),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='majoration_heures_complementaires',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Majoration des heures complémentaires'),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='majoration_heures_supps_contractuelles',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=5, verbose_name='Majoration des heures supplémentaires contractuelles'),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='majoration_heures_supps_non_contractuelles',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=5, verbose_name='Majoration des heures supplémentaires non contractuelles'),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='nb_heures_accueil_jour',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name="Nombre d'heures d'accueil par jour"),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='nb_heures_semaine',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name="Nombre d'heures par semaine"),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='nb_heures_supps_contractuelles_mois',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name="Nombre d'heures supplémentaires contractuelles par mois"),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='nb_semaines_programmees',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Nombre de semaines programmées'),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='remuneration_horaire_brute',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Rémunération horaire brute'),
        ),
        migrations.AlterField(
            model_name='jourtravail',
            name='heures_complementaires',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Heures complémentaires'),
        ),
        migrations.AlterField(
            model_name='jourtravail',
            name='heures_effectuees',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Heures effectuées (hors complémentaires/supps)'),
        ),
        migrations.AlterField(
            model_name='jourtravail',
            name='heures_supplementaires',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Heures supplémentaires'),
        ),
    ]
