# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-16 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assmat', '0004_auto_20170913_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletinsalaire',
            name='nb_jours_moins_8h',
            field=models.IntegerField(default=0, verbose_name='Nombre de jours travaillés de moins de 8h dans le mois'),
        ),
        migrations.AddField(
            model_name='bulletinsalaire',
            name='nb_jours_plus_8h',
            field=models.IntegerField(default=0, verbose_name='Nombre de jours travaillés de 8h et plus dans le mois'),
        ),
        migrations.AddField(
            model_name='bulletinsalaire',
            name='nb_semaines_travailles_mois',
            field=models.IntegerField(default=0, verbose_name='Nombre de semaines travaillées dans le mois'),
        ),
        migrations.AddField(
            model_name='contrat',
            name='nb_enfants_moins_15_ans',
            field=models.IntegerField(default=0, verbose_name="Nombre d'enfants à charge du salairé de moins de 15 ans"),
        ),
        migrations.AlterField(
            model_name='bulletinsalaire',
            name='cumul_nb_semaines_travaillees',
            field=models.IntegerField(default=0, verbose_name='Cumul nombre de semaines travaillées'),
        ),
    ]
