# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-07 12:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('compta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieEpargne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=256, verbose_name='Libellé')),
            ],
        ),
        migrations.CreateModel(
            name='Epargne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solde', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Solde')),
                ('pourcentage_alloue', models.IntegerField(verbose_name="Pourcentage des versements d'épargne alloué")),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compta.CategorieEpargne', verbose_name='Catégorie')),
                ('utilisateurs', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Utilisateurs')),
            ],
        ),
        migrations.CreateModel(
            name='OperationEpargne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Montant')),
                ('epargne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compta.Epargne', verbose_name='Epargne')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compta.Operation', verbose_name='Opération réelle initiale')),
            ],
        ),
        migrations.AddField(
            model_name='budget',
            name='utilisateurs',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Utilisateurs'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='budget',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Budget'),
        ),
    ]
