# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-07 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compta', '0002_auto_20170807_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='compte',
            name='libelle',
            field=models.CharField(max_length=128, null=True, verbose_name='Libellé'),
        ),
        migrations.AlterField(
            model_name='compte',
            name='numero_compte',
            field=models.CharField(max_length=128, verbose_name='Numéro de compte'),
        ),
    ]
