# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-09 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compta', '0003_auto_20170807_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='compte',
            name='epargne',
            field=models.BooleanField(default=False, verbose_name="Le compte est un compte d'épargne"),
        ),
    ]
