# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-09 20:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compta', '0004_compte_epargne'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationepargne',
            name='epargne',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='compta.Epargne', verbose_name='Epargne'),
        ),
    ]
