# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-10 20:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('compta', '0005_auto_20170809_2224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Identifiant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banque', models.CharField(choices=[('CM', 'Crédit Mutuel')], max_length=128, verbose_name='Banque')),
                ('login', models.CharField(max_length=128, verbose_name='Login')),
                ('mot_de_passe', models.CharField(max_length=128, verbose_name='Mot de passe')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
        ),
        migrations.RemoveField(
            model_name='compte',
            name='banque',
        ),
        migrations.RemoveField(
            model_name='compte',
            name='login',
        ),
        migrations.RemoveField(
            model_name='compte',
            name='mot_de_passe',
        ),
        migrations.AddField(
            model_name='compte',
            name='identifiant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='compta.Identifiant', verbose_name='Identifiant'),
        ),
    ]
