# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-10 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compta', '0006_auto_20170810_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='identifiant',
            name='encrypted',
            field=models.BooleanField(default=False),
        ),
    ]
