# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-12 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compta', '0008_auto_20170811_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='type',
            field=models.CharField(choices=[('1', 'Dépense'), ('2', 'Recette'), ('3', 'Hors Budget')], default='1', max_length=1, verbose_name='Type'),
        ),
    ]
