# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-12 09:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compta', '0009_categorie_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='utilisateurs',
        ),
        migrations.AddField(
            model_name='budget',
            name='compte_associe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='compta.Compte', verbose_name='Compte associé'),
        ),
    ]
