# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-12 09:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compta', '0010_auto_20170812_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='compte_associe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compta.Compte', verbose_name='Compte associé'),
        ),
    ]
