# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-12 09:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compta', '0012_auto_20170812_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compte',
            name='identifiant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compta.Identifiant', verbose_name='Identifiant'),
        ),
    ]
