# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-12 10:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compta', '0013_auto_20170812_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='categorie',
        ),
        migrations.AddField(
            model_name='operation',
            name='budget',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='compta.Budget', verbose_name='Budget'),
        ),
        migrations.AddField(
            model_name='operation',
            name='hors_budget',
            field=models.BooleanField(default=False, verbose_name='Hors Budget'),
        ),
    ]
