# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-12 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compta', '0014_auto_20170812_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorie',
            name='type',
        ),
        migrations.AddField(
            model_name='operation',
            name='recette',
            field=models.BooleanField(default=False, verbose_name='Recette'),
        ),
    ]
