# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 21:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compta', '0016_operation_contributeur'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='avance',
            field=models.BooleanField(default=False, verbose_name='Avance'),
        ),
        migrations.AlterField(
            model_name='compte',
            name='libelle',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Libellé'),
        ),
        migrations.AlterField(
            model_name='compte',
            name='solde',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Solde'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='budget',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compta.Budget', verbose_name='Budget'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='contributeur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Contributeur'),
        ),
        migrations.AlterField(
            model_name='operationepargne',
            name='epargne',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compta.Epargne', verbose_name='Epargne'),
        ),
    ]
