# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 21:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compta', '0017_auto_20170816_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='saisie_manuelle',
            field=models.BooleanField(default=False, verbose_name='Saisie manuellement'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='recette',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recettes', to=settings.AUTH_USER_MODEL, verbose_name='Revenus pour cette personne'),
        ),
    ]
