# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compta', '0019_auto_20170818_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='avance_debit',
            field=models.BooleanField(default=False, verbose_name='Avance pour débit(s) futur(s)'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='avance',
            field=models.BooleanField(default=False, verbose_name='Avance sur budget'),
        ),
    ]
