# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compta', '0020_auto_20170826_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='avance_debit',
            field=models.BooleanField(default=False, verbose_name='Avance sur débit(s) futur(s)'),
        ),
    ]
